# Generated by Django 4.1.2 on 2022-10-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.customer'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.warehouse'),
        ),
        migrations.AlterField(
            model_name='level',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.rack'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.section'),
        ),
        migrations.AlterField(
            model_name='palletproduct',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.pallet'),
        ),
        migrations.AlterField(
            model_name='palletproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.product'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.warehouse'),
        ),
        migrations.AlterField(
            model_name='section',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.level'),
        ),
    ]
