# Generated by Django 4.1.2 on 2022-10-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('bodegas', '0002_alter_inventory_customer_alter_inventory_product_and_more'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpalletproduct',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.inputwarehouse'),
        ),
        migrations.AlterField(
            model_name='inputpalletproduct',
            name='pallet_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.palletproduct'),
        ),
        migrations.AlterField(
            model_name='inputwarehouse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.request'),
        ),
        migrations.AlterField(
            model_name='inputwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.warehouse'),
        ),
        migrations.AlterField(
            model_name='outputpalletproduct',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.outputwarehouse'),
        ),
        migrations.AlterField(
            model_name='outputpalletproduct',
            name='pallet_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.palletproduct'),
        ),
        migrations.AlterField(
            model_name='outputwarehouse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.request'),
        ),
        migrations.AlterField(
            model_name='outputwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegas.warehouse'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.customer'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.product'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.request'),
        ),
    ]
